<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns="http://www.w3.org/1999/xhtml">

    <!-- Include Bootstrap stylesheet -->
    <xsl:output method="xml" indent="yes" doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"/>
    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml">
            <head>
                <meta charset="UTF-8" />
                <meta http-equiv="X-UA-Compatible" content="IE=7"/>
                <meta http-equiv="X-UA-Compatible" content="ie=edge" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />s

                <title>Home Sitemap</title>
                <!-- Link to Bootstrap CSS file -->
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
            </head>
            <body>
                <header class="bg-dark text-white py-4 mt-n3">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">
                                <h1>XML Sitemap</h1>
                                <p>This sitemap is generated by own engine, this is an XML Sitemap, meant to be consumed by search engines like Google or Bing.</p>
                                <p>You can find more information about XML Sitemaps at <a href="https://sitemaps.org" target="_blank">sitemaps.org</a>.</p>
                            </div>
                        </div>
                    </div>
                </header>

                <main class="container table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Location</th>
                                <th scope="col">Last Modified</th>
                                <th scope="col">Change Frequency</th>
                                <th scope="col">Priority</th>
                            </tr>
                        </thead>
                        <tbody>
                            <xsl:apply-templates select="sitemap" />
                        </tbody>
                    </table>
                </main>
            </body>
        </html>
    </xsl:template>

    <!-- Template for processing each sitemap element -->
    <xsl:template match="sitemap">
        <tr>
            <td>
                <xsl:value-of select="loc"/>
            </td>
            <td>
                <xsl:value-of select="lastmod"/>
            </td>
            <td>
                <xsl:value-of select="changefreq"/>
            </td>
            <td>
                <xsl:value-of select="priority"/>
            </td>
        </tr>
    </xsl:template>
</xsl:stylesheet>
